export const PROVINCES_REQUEST = "PROVINCES_REQUEST"
export const PROVINCES_SUCCESS = "PROVINCES_SUCCESS"
export const PROVINCES_FAIL = "PROVINCES_FAIL"

export const PROVINCE_SHIPPING_REQUEST = "PROVINCE_SHIPPING_REQUEST"
export const PROVINCE_SHIPPING_SUCCESS = "PROVINCE_SHIPPING_SUCCESS"
export const PROVINCE_SHIPPING_FAIL = "PROVINCE_SHIPPING_FAIL"

export const DISTRICT_SHIPPING_REQUEST = "DISTRICT_SHIPPING_REQUEST"
export const DISTRICT_SHIPPING_SUCCESS = "DISTRICT_SHIPPING_SUCCESS"
export const DISTRICT_SHIPPING_FAIL = "DISTRICT_SHIPPING_FAIL"

export const PROVINCE_BILLING_REQUEST = "PROVINCE_BILLING_REQUEST"
export const PROVINCE_BILLING_SUCCESS = "PROVINCE_BILLING_SUCCESS"
export const PROVINCE_BILLING_FAIL = "PROVINCE_BILLING_FAIL"

export const DISTRICT_BILLING_REQUEST = "DISTRICT_BILLING_REQUEST"
export const DISTRICT_BILLING_SUCCESS = "DISTRICT_BILLING_SUCCESS"
export const DISTRICT_BILLING_FAIL = "DISTRICT_BILLING_FAIL"
