export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"

export const DECREASE_QUANTITY = "DECREASE_QUANTITY"
export const INCREASE_QUANTITY = "INCREASE_QUANTITY"

export const GET_NUMBER_CART = "GET_NUMBER_CART"