export const PAYMENT_REQUEST = "PAYMENT_REQUEST"
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
export const PAYMENT_FAIL = "PAYMENT_FAIL"

export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST"
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS"
export const CHECKOUT_FAIL = "CHECKOUT_FAIL"

export const ORDER_LIST_ALL_REQUEST = "ORDER_LIST_ALL_REQUEST"
export const ORDER_LIST_ALL_SUCCESS = "ORDER_LIST_ALL_SUCCESS"
export const ORDER_LIST_ALL_FAIL = "ORDER_LIST_ALL_FAIL"

export const ORDER_LIST_UNPAID_REQUEST = "ORDER_LIST_UNPAID_REQUEST"
export const ORDER_LIST_UNPAID_SUCCESS = "ORDER_LIST_UNPAID_SUCCESS"
export const ORDER_LIST_UNPAID_FAIL = "ORDER_LIST_UNPAID_FAIL"

export const ORDER_LIST_PROCESSING_REQUEST = "ORDER_LIST_PROCESSING_REQUEST"
export const ORDER_LIST_PROCESSING_SUCCESS = "ORDER_LIST_PROCESSING_SUCCESS"
export const ORDER_LIST_PROCESSING_FAIL = "ORDER_LIST_PROCESSING_FAIL"

export const ORDER_LIST_DELIVERING_REQUEST = "ORDER_LIST_DELIVERING_REQUEST"
export const ORDER_LIST_DELIVERING_SUCCESS = "ORDER_LIST_DELIVERING_SUCCESS"
export const ORDER_LIST_DELIVERING_FAIL = "ORDER_LIST_DELIVERING_FAIL"

export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST"
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS"
export const CANCEL_ORDER_FAIL = "CANCEL_ORDER_FAIL"

export const ORDER_LIST_CANCEL_REQUEST = "ORDER_LIST_CANCEL_REQUEST"
export const ORDER_LIST_CANCEL_SUCCESS = "ORDER_LIST_CANCEL_SUCCESS"
export const ORDER_LIST_CANCEL_FAIL = "ORDER_LIST_CANCEL_FAIL"
