export const PRODUCT_LIST_NEW_REQUEST = "PRODUCT_LIST_NEW_REQUEST"
export const PRODUCT_LIST_NEW_SUCCESS = "PRODUCT_LIST_NEW_SUCCESS"
export const PRODUCT_LIST_NEW_FAIL = "PRODUCT_LIST_NEW_FAIL"

export const PRODUCT_LIST_HOT_REQUEST = "PRODUCT_LIST_HOT_REQUEST"
export const PRODUCT_LIST_HOT_SUCCESS = "PRODUCT_LIST_HOT_SUCCESS"
export const PRODUCT_LIST_HOT_FAIL = "PRODUCT_LIST_HOT_FAIL"

export const PRODUCT_LIST_RELATED_REQUEST = "PRODUCT_LIST_RELATED_REQUEST"
export const PRODUCT_LIST_RELATED_SUCCESS = "PRODUCT_LIST_RELATED_SUCCESS"
export const PRODUCT_LIST_RELATED_FAIL = "PRODUCT_LIST_RELATED_FAIL"

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

export const PRODUCT_LIST_SUGGESTION_REQUEST = "PRODUCT_LIST_SUGGESTION_REQUEST"
export const PRODUCT_LIST_SUGGESTION_SUCCESS = "PRODUCT_LIST_SUGGESTION_SUCCESS"
export const PRODUCT_LIST_SUGGESTION_FAIL = "PRODUCT_LIST_SUGGESTION_FAIL"

export const PRODUCT_CATEGORY_REQUEST = "PRODUCT_CATEGORY_REQUEST"
export const PRODUCT_CATEGORY_SUCCESS = "PRODUCT_CATEGORY_SUCCESS"
export const PRODUCT_CATEGORY_FAIL = "PRODUCT_CATEGORY_FAIL"

export const PRODUCT_BREED_REQUEST = "PRODUCT_BREED_REQUEST"
export const PRODUCT_BREED_SUCCESS = "PRODUCT_BREED_SUCCESS"
export const PRODUCT_BREED_FAIL = "PRODUCT_BREED_FAIL"

export const PRODUCT_LIST_NAME_REQUEST = "PRODUCT_LIST_NAME_REQUEST"
export const PRODUCT_LIST_NAME_SUCCESS = "PRODUCT_LIST_NAME_SUCCESS"
export const PRODUCT_LIST_NAME_FAIL = "PRODUCT_LIST_NAME_FAIL"

export const PRODUCT_LIST_PAGE_REQUEST = "PRODUCT_LIST_PAGE_REQUEST"
export const PRODUCT_LIST_PAGE_SUCCESS = "PRODUCT_LIST_PAGE_SUCCESS"
export const PRODUCT_LIST_PAGE_FAIL = "PRODUCT_LIST_PAGE_FAIL"

export const PRODUCT_WISH_LIST_REQUEST = "PRODUCT_WISH_LIST_REQUEST"
export const PRODUCT_WISH_LIST_SUCCESS = "PRODUCT_WISH_LIST_SUCCESS"
export const PRODUCT_WISH_LIST_FAIL = "PRODUCT_WISH_LIST_FAIL"


export const ADD_PRODUCT_WISH_LIST_SUCCESS = "ADD_PRODUCT_WISH_LIST_SUCCESS"
export const ADD_PRODUCT_WISH_LIST_FAIL = "ADD_PRODUCT_WISH_LIST_FAIL"
export const ADD_PRODUCT_WISH_LIST_REQUEST= "ADD_PRODUCT_WISH_LIST_REQUEST"

export const PRODUCT_GET_REVIEW_REQUEST = "PRODUCT_GET_REVIEW_REQUEST"
export const PRODUCT_GET_REVIEW_SUCCESS = "PRODUCT_GET_REVIEW_SUCCESS"
export const PRODUCT_GET_REVIEW_FAIL = "PRODUCT_GET_REVIEW_FAIL"


export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST"
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS"
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL"
