export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_LOGOUT = "USER_LOGOUT"

export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST"
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS"
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL"
export const USER_DETAIL_RESET = "USER_DETAIL_RESET"

export const USER_UPDATE_AVATAR_REQUEST = "USER_UPDATE_AVATAR_REQUEST"
export const USER_UPDATE_AVATAR_SUCCESS = "USER_UPDATE_AVATAR_SUCCESS"
export const USER_UPDATE_AVATAR_FAIL = "USER_UPDATE_AVATAR_FAIL"

export const USER_CHANGE_PASSWORD_REQUEST = "USER_CHANGE_PASSWORD_REQUEST"
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS"
export const USER_CHANGE_PASSWORD_FAIL = "USER_CHANGE_PASSWORD_FAIL"

export const USER_UPDATE_INFORMATION_REQUEST = "USER_UPDATE_INFORMATION_REQUEST"
export const USER_UPDATE_INFORMATION_SUCCESS = "USER_UPDATE_INFORMATION_SUCCESS"
export const USER_UPDATE_INFORMATION_FAIL = "USER_UPDATE_INFORMATION_FAIL"

export const REFRESH_TOKEN = "REFRESH_TOKEN"


